language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

# run build against hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly
    - php: 7.0

# ensure compatibility with different core versions
env:
  - YII2_VERSION=2.0.0
  - YII2_VERSION=2.0.1
  - YII2_VERSION=2.0.2
  - YII2_VERSION=2.0.3
  - YII2_VERSION=@dev


# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:1.0.0"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer require "yiisoft/yii2:$YII2_VERSION" --prefer-dist --no-interaction
  - travis_retry composer install --prefer-dist --no-interaction
  - composer show -i

before_script:
  - psql --version
  - psql -U postgres -c 'CREATE DATABASE yiitest;';
  - psql -U postgres yiitest < tests/data/pgsql.sql
  - echo "<?php unset(\$config['databases']['pgsql']['fixture']);" > tests/data/config.local.php

  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi

script:
  - phpunit --verbose $PHPUNIT_FLAGS

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
